[project]
name = "notebooks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Said Rodrigues", email = "coderflemis@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "connectorx>=0.4.4",
    "matplotlib>=3.10.8",
    "numpy>=2.3.5",
    "polars>=1.36.1",
    "pyarrow>=22.0.0",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
    "tensorflow>=2.20.0",
    "xgboost>=3.1.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
