# TODO: make db and redis with healthcheck
services:
  redis:
    image: redis:8.4.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass senha

  browser:
    build:
      context: ./
      dockerfile: ./docker/browser.Dockerfile
    image: ghcr.io/taldoflemis/clutch-or-predict/browser
    ports:
      - 9222:9222
    environment:
      # Socat to forward the debug port on port 9222
      CLUTCHORPREDICT_BROWSER__DEBUG_PORT: 9223
      CLUTCHORPREDICT_BROWSER__DEBUG_ADDRESS: 0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9222/json/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
      start_interval: 1s

  worker:
    build:
      context: ./
      dockerfile: ./docker/celery-worker.Dockerfile
    image: ghcr.io/taldoflemis/clutch-or-predict/celery-worker
    depends_on:
      - redis
      - db
    environment:
      CLUTCHORPREDICT_REDIS__HOST: "localhost"
      CLUTCHORPREDICT_REDIS__PASSWORD: senha
      CLUTCHORPREDICT_CELERY__WORKER_CONCURRENCY: 10
      CLUTCHORPREDICT_CELERY__WORKER_LOG_LEVEL: "DEBUG"
      CLUTCHORPREDICT_BROWSER__USE_CDP: true
      CLUTCHORPREDICT_BROWSER__DEBUG_PORT: 9222
      CLUTCHORPREDICT_BROWSER__DEBUG_ADDRESS: browser

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    volumes:
      - redis-insight-data:/data
    depends_on:
      - redis
  db:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: marcelinho
      POSTGRES_PASSWORD: molodoy
      POSTGRES_DB: cs2_stats
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data
volumes:
  redis_data:
  redis-insight-data:
  postgres-data:
