[project]
name = "clutch_or_predict"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "celery[redis]>=5.6.0",
  "flower>=2.0.1",
  "numpy>=2.3.5",
  "pandas>=2.3.3",
  "parsel>=1.10.0",
  "patchright>=1.56.0",
  "pydantic>=2.12.5",
  "redis>=5.0.0",
]

[tool.uv]
package = true

[dependency-groups]
dev = [
    "ruff>=0.14.8",
]

[project.scripts]
scraper = "scraper:scrape"
frontier = "scraper.frontier:main"
